server: # Configuration for the REST and WebSocket server
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false # Enable or disable HTTP/2 support

plugins:
  youtube:
    enabled: true # Whether this source can be used.
    allowSearch: true # Whether "ytsearch:" and "ytmsearch:" can be used.
    allowDirectVideoIds: true # Whether just video IDs can match. If false, only complete URLs will be loaded.
    allowDirectPlaylistIds: true # Whether just playlist IDs can match. If false, only complete URLs will be loaded.
    # The clients to use for track loading. See below for a list of valid clients.
    # Clients are queried in the order they are given (so the first client is queried first and so on...)
    clients:
      - MUSIC
      - WEB
      - TVHTML5EMBEDDED
      - ANDROID_TESTSUITE

lavalink:
  plugins:
    # Specify the Lavalink plugin version or snapshot
    - dependency: 'dev.lavalink.youtube:youtube-plugin:1.8.3'
      snapshot: false # Use snapshot version if true
  server:
    password: 'wS2WzhJDpPLuRkBmMqXEyAGx9vC7QHn8dVTNeYKrb435Zt6'
    sources: # Configure available sources
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: false
      local: false
    filters:
      volume: true
      equalizer: false
      karaoke: false
      timescale: false
      tremolo: false
      vibrato: false
      distortion: false
      rotation: false
      channelMix: false
      lowPass: false
    bufferDurationMs: 400 # Buffer duration (ms); higher values handle GC pauses better
    frameBufferDurationMs: 5000 # Amount of audio to keep buffered (ms)
    opusEncodingQuality: 10 # Opus encoder quality (0-10); higher values are better but more CPU-intensive
    resamplingQuality: HIGH # Resampling quality (LOW, MEDIUM, HIGH); HIGH uses more CPU but provides better audio quality
    trackStuckThresholdMs: 2000 # Time threshold for track to be considered stuck (ms)
    useSeekGhosting: true # Enable seek ghosting to smooth out seeks
    youtubePlaylistLoadLimit: 6 # Number of pages to load per playlist (100 items per page)
    playerUpdateInterval: 5 # Frequency of player updates to clients (seconds)
    youtubeSearchEnabled: true # Enable YouTube search
    soundcloudSearchEnabled: true # Enable SoundCloud search
    gc-warnings: false # Enable garbage collection warnings
