server: # Configuration for the REST and WebSocket server
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false # Enable or disable HTTP/2 support

plugins:
  youtube:
    enabled: true # Enable or disable the YouTube source
    allowSearch: true # Allow "ytsearch:" and "ytmsearch:" queries
    allowDirectVideoIds: true # Allow direct video IDs; if false, only full URLs are accepted
    allowDirectPlaylistIds: true # Allow direct playlist IDs; if false, only full URLs are accepted
    clients: # List of clients to query for track loading, in order of preference
      - MUSIC
      - ANDROID_TESTSUITE
      - WEB
      - TVHTML5EMBEDDED

lavalink:
  plugins:
    # Specify the Lavalink plugin version or snapshot
    - dependency: 'dev.lavalink.youtube:youtube-plugin:1.5.0'
      snapshot: false # Use snapshot version if true
  server:
    password: 'wS2WzhJDpPLuRkBmMqXEyAGx9vC7QHn8dVTNeYKrb435Zt6'
    sources: # Configure available sources
      youtube: false # Deprecated, use https://github.com/lavalink-devs/youtube-source#plugin
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: false # Warning: Enabling HTTP without a proxy exposes server IP
      local: false
    filters: # Enabled by default
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400 # Buffer duration (ms); higher values handle GC pauses better
    frameBufferDurationMs: 5000 # Amount of audio to keep buffered (ms)
    opusEncodingQuality: 10 # Opus encoder quality (0-10); higher values are better but more CPU-intensive
    resamplingQuality: HIGH # Resampling quality (LOW, MEDIUM, HIGH); HIGH uses more CPU but provides better audio quality
    trackStuckThresholdMs: 10000 # Time threshold for track to be considered stuck (ms)
    useSeekGhosting: true # Enable seek ghosting to smooth out seeks
    youtubePlaylistLoadLimit: 6 # Number of pages to load per playlist (100 items per page)
    playerUpdateInterval: 5 # Frequency of player updates to clients (seconds)
    youtubeSearchEnabled: true # Enable YouTube search
    soundcloudSearchEnabled: true # Enable SoundCloud search
    gc-warnings: true # Enable garbage collection warnings
